version: "3"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    env_file:
   
      - ./.env 
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'

  user:
    build:
      dockerfile: Dockerfile
      context: ./User
    container_name: user
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - postgres-db
      - rabbitmq
    volumes:
      - .:/app
      - /app/User/node_modules
    env_file:
      - ./User/.env

  vendor:
    build:
      dockerfile: Dockerfile
      context: ./Vendor
    container_name: Vendor
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres-db
      - rabbitmq
    volumes:
      - .:/app
      - /app/Vendor/node_modules
    env_file:
      - ./Vendor/.env

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - user
      - vendor
   
    ports:
      - 80:80
