name: Microservice CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Debug (User Directory)
      run: |
        ls -la ./user
        cat ./user/package.json

    - name: Install Dependencies (User)
      working-directory: ./user
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Debug (Vendor Directory)
      run: |
        ls -la ./vendor
        cat ./vendor/package.json

    - name: Install Dependencies (Vendor)
      working-directory: ./vendor
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Deploy to Production (Replace with your deployment script)
      run: |
        echo "Deploying to production..."
