
name: micro_service

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: run user
      working-directory: ./user
      run: |
        npm build
        npm start
    - name: run vendor
      working-directory: ./vendor
      run: |
        npm build
        npm start
       
      
  
