name: Microservices CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-user:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: 'https://registry.yarnpkg.com'

    - name: Install Dependencies (User)
      working-directory: ./user
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Deploy User Microservice (Replace with your deployment script)
      run: |
        echo "Deploying User microservice..."

  build-and-deploy-vendor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: 'https://registry.yarnpkg.com'

    - name: Install Dependencies (Vendor)
      working-directory: ./vendor
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Deploy Vendor Microservice (Replace with your deployment script)
      run: |
        echo "Deploying Vendor microservice..."
